version: 2.4.0.{build}
image: Visual Studio 2017
install:
- cinst gtksharp -y
build_script:
- set BASE=%APPVEYOR_BUILD_FOLDER%
- set BUILD_VERSION=000%APPVEYOR_BUILD_NUMBER%
- set BUILD_VERSION=2.4.0-build%BUILD_VERSION:~-4%
- echo Downloading XamMac.dll for build..
- mkdir %BASE%\artifacts\core\Release\net45
- appveyor DownloadFile %XAMMAC_LOCATION%/XamMac.dll -FileName "%BASE%\artifacts\core\Release\net45\XamMac.dll"
- msbuild -t:Package -p:BuildVersion=%BUILD_VERSION% build\Build.proj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:NoSummary
test: off
#test_script:
#- nunit-console --framework=4.5 --include=TestPlatform artifacts/Release/net45/test/Eto.Test.dll
artifacts:
- path: artifacts/nuget/Release/*.nupkg
  name: nuget
branches:
  only:
  - develop
  - master
skip_branch_with_pr: true
deploy:
- provider: Environment
  name: MyGet
  on:
    branch: develop
